### ISSUE TITLE
some bad case

### ISSUE THREAD

**Issue by liangzh-404** [cristianvasquez/obsidian-prettify#1]
1. it will change todo list from "- [ ]" to "* [ ]" which make it not work
2. test case below
```
1. fjlkefjl
    1. feafe
2. feafea
3. feaf
    1. fea
3. fefe
```
expect to get 
```
1. fjlkefjl
    1. feafe
2. feafea
3. feaf
    1. fea
4. fefe
```
but get
```
1. fjlkefjl
  2. feafe
* feafea
* feaf
  1. fea
* fefe
```
still a nice try! thank you for the idea~

**Comment by santiyounger** [comment]
@liangzh-404  checklists do work for me, do you have a checklist example where it fails? all it does for me is change from `- [ ]` to `* [ ]` it'd be better for it not to change, but it still works without any issues.

Regarding the numbers situations, I get that same result, which would be great to fix.

Apart from that I wanted to thank @liangzh-404 for the amazing plugin, can't wait to see this plugin get more popularity in obsidian! It's super useful

**Comment by cristianvasquez** [comment]
Hi @liangzh-404 @santiyounger, thanks for the reports!.

I added a new version 0.0.2 that fixed the issues

**Comment by santiyounger** [comment]
thank you @cristianvasquez it works great for me, appreciate it!
