### ISSUE TITLE
No response when using this plugin

### ISSUE THREAD

**Issue by wenlzhang** [cristianvasquez/obsidian-prettify#10]
I tried to improve the note format with the latest version of this plugin on Obsidian version 0.9.19 and macOS Big Sur, but there was no change in the note content.

**Comment by cristianvasquez** [comment]
Hello @wenlzhang did you try with the command menu?

**Comment by wenlzhang** [comment]
Using the plugin from Cmd+P changes the note format now. Probably the default hotkey was taken by other apps, but I can change that.

Another question is that every time I run the plugin, a new YAML header would be generated right before the selected part of the note, although I only selected part of the note and the header already exists at the beginning of the note. Is this the desired behaviour? The header settings are given as follows:
<img width="1137" alt="Screenshot 2020-12-08 at 08 12 56" src="https://user-images.githubusercontent.com/44930227/101420483-905a2500-38f2-11eb-9573-fb8bd06b1b20.png">

**Comment by cristianvasquez** [comment]
Hello, @wenlzhang a new YAML header generated in the middle is not the expected behavior. I'm trying to reproduce it, but I cant'

**Comment by wenlzhang** [comment]
@cristianvasquez I am not sure why, but it's working now when I just tried it. Now I have Obsidian version 0.9.22, it may be related to this... Anyway, you can probably close this.
