### ISSUE TITLE
Second backslashes removed in the math block, causing LaTeX messup

### ISSUE THREAD

**Issue by psyguy** [cristianvasquez/obsidian-prettify#12]
Hi there,

If you want to write multiline/matrix in a math block in your text, you need to use `\\`. However, the plugin removes one of the backslashes, messing up the math block.

For instance, for the following matrix:

``` md
$$
\begin{bmatrix}
a && b \\
c && d
\end{bmatrix}
$$
```
Should render like this:
![image](https://user-images.githubusercontent.com/8527082/100724663-691bc900-33c3-11eb-8411-7e8e42e40e96.png)

But when the document is prettified, `\\` becomes `\`:
``` md
$$
\begin{bmatrix}
a && b \
c && d
\end{bmatrix}
$$
```

Which renders to:
![image](https://user-images.githubusercontent.com/8527082/100724961-bb5cea00-33c3-11eb-94f6-3296d0b53ac6.png)

It should have a quick fix, right?

Thanks in advance!

**Comment by cristianvasquez** [comment]
Thanks for reporting this!. 

It seems that it doesn't like double slashes \\

I'll try to fix it.

**Comment by cristianvasquez** [comment]
Hi @psyguy ! I updated the plugin ot version 0.0.4 with a fix to this

**Comment by psyguy** [comment]
Thanks 😌
