### ISSUE TITLE
{{date:YYYY-MM-DD}} expands to 2020-12-05T00:00:00.000Z

### ISSUE THREAD

**Issue by lilruffian** [cristianvasquez/obsidian-prettify#13]
Thanks for this plug. One small thing though.

{{date:YYYY-MM-DD}} seems to expand to 2020-12-05T00:00:00.000Z.

However, if I add a character after }}, like a period in this example:
`{{date:YYYY-MM-DD}}.`
Then it expands correctly to `2020-12-05.`

**Comment by cristianvasquez** [comment]
Hi!.. thanks for reporting. Where this happens?

**Comment by lilruffian** [comment]
In the frontmatter. 

Here's what it looks like **before** expansion"
```
---
Date: {{date:YYYY-MM-DD}}
Alias: []
Tags: []

---
```

Here's what it looks like **after** expansion
```
---
Date: 2020-12-05T00:00:00.000Z
Alias: []
Tags: []

---
```

**Comment by cristianvasquez** [comment]
Hi!

I think you can change the frontmatter template in the plugin settings?

![image](https://user-images.githubusercontent.com/361916/102712668-2e6ec780-42c3-11eb-820e-cc8fed6bf1c8.png)
