### ISSUE TITLE
Configurable number of spaces for list indent

### ISSUE THREAD

**Issue by NomarCub** [cristianvasquez/obsidian-prettify#15]
This plugin uses 4 spaces for indenting lists and 3 after the bullet (`-`) for lists.
I'd like these to be configurable to be in sync with my other tools.

**Comment by cristianvasquez** [comment]
hi!.. can you give me an example?

**Comment by NomarCub** [comment]
I use the Prettier plugin for VSCode that formats it my way and the markdownlint plugin in VSCode that lints it this way. I can turn off these rules for the linter, but can't set different amount of spaces, and also can't find a way to configure Prettier in this detail.

**Comment by cristianvasquez** [comment]
It's not easy for me to change the number of spaces. 

I'm thinking about changing the 'prettification' to be done by prettier. How do you tell Prettier to format it in your way?

**Comment by NomarCub** [comment]
I can't, there's no settings for it as far as I know. By my way I just meant Prettier's default settings (that happen to align with markdownlint), which you can do with the 'Format document' command. It might not be worth it to change your formatter because of this, but this is my use case.

**Comment by cristianvasquez** [comment]
Hi @NomarCub I updated the plugin to select the number of spaces. I hope it works for you.

**Comment by tonyxiao** [comment]
@cristianvasquez the one issue is that it seems to add spaces AFTER the bullet too when I expected it to only add spaces *before* the bullet. This is after choosing `big` for list indent
![CleanShot 2021-10-27 at 08 48 20](https://user-images.githubusercontent.com/696842/138981486-df3660fc-4c20-4816-bf44-6048af081a14.gif)
.

**Comment by cristianvasquez** [comment]
> I can't, there's no settings for it as far as I know. By my way I just meant Prettier's default settings (that happen to align with markdownlint), which you can do with the 'Format document' command. It might not be worth it to change your formatter because of this, but this is my use case.

Hi @NomarCub ,  there is a prettier plugin for obsidian too, https://github.com/hipstersmoothie/obsidian-plugin-prettier , perhaps you could use your config there.

**Comment by cristianvasquez** [comment]
> @cristianvasquez the one issue is that it seems to add spaces AFTER the bullet too when I expected it to only add spaces _before_ the bullet. This is after choosing `big` for list indent ![CleanShot 2021-10-27 at 08 48 20](https://user-images.githubusercontent.com/696842/138981486-df3660fc-4c20-4816-bf44-6048af081a14.gif) .

Ho @tonyxiao , in the next week I'll add a 'post-processing function' (so you can replace a regular expression for example),  that would take less time (from my side) than looking into the library to change that behavior.

**Comment by cristianvasquez** [comment]
I added a tab or space option :)
