### ISSUE TITLE
Use TAB char instead of spaces

### ISSUE THREAD

**Issue by dariuszkowalski-com** [cristianvasquez/obsidian-prettify#19]
I would like to have an option to use TAB char instead of spaces in lists
I've found that MD files with tabs are more usable and I can e.g. use a CSS snippet whish visualize intended levels. 
When I have got spaces it doesn't work

**Comment by cristianvasquez** [comment]
I added the option for the next version :)

**Comment by Icelk** [comment]
I see no options for this still.

**Comment by ytechie** [comment]
Is there way to do this? I have notes with spaces (pasted in elsewhere), and want to convert to tabs for the lists.
