### ISSUE TITLE
How to change the shortcut?

### ISSUE THREAD

**Issue by OnkelTem** [cristianvasquez/obsidian-prettify#2]
`Ctrl+Alt+L` is called a _default_ shortcut in the plugin description. So how to customize it?

This combination is blocking screen on Linux Kubuntus.

**Comment by cristianvasquez** [comment]
Hello @OnkelTem you have to go into Settings -> Hotkeys and search 'Markdown prettifier'. there you can change it.

![image](https://user-images.githubusercontent.com/361916/99196434-a01b9900-278c-11eb-8a21-08efa1f3d044.png)

**Comment by OnkelTem** [comment]
Ah, that! Thank you.

I simply opened the Markdown prettier page only, and it was empty :)

![image](https://user-images.githubusercontent.com/114060/99262795-70719d00-282f-11eb-815b-cf1fd9308fed.png)
 
But yeah, now I found it.
