### ISSUE TITLE
LaTeX Equation Formatted Incorrectly

### ISSUE THREAD

**Issue by alphawent** [cristianvasquez/obsidian-prettify#21]
It seems that LaTeX formulas with multiple lines will be formatted incorrectly  
P.S. Markdown Prettifier version 0.0.4  
e.g.

```markdown
$$
\gamma
=
\alpha
+ \beta
$$
```
will be transformed into
```markdown
# $$
\gamma

\alpha

*   \beta

$$
```

**Comment by cristianvasquez** [comment]
Hello @alphawent , I cannot reproduce this.

Are you using v.0.0.4 ?

**Comment by cristianvasquez** [comment]
I think this was fixed in he last version
