### ISSUE TITLE
remain UTF char as was entered

### ISSUE THREAD

**Issue by dariuszkowalski-com** [cristianvasquez/obsidian-prettify#22]
I am using Emoji to create tags.
For example for people I am using:
![image](https://user-images.githubusercontent.com/37656900/102755219-65e67e00-436e-11eb-87b5-abc5faaf9db1.png)

After run this plugin it sometime change to:
![image](https://user-images.githubusercontent.com/37656900/102755380-975f4980-436e-11eb-9f4e-8d500e8058c6.png)

I would like to make it remains untought

**Comment by cristianvasquez** [comment]
Hello! thanks for the report. 

I found it is because a lib I use. I reported it here: https://github.com/nodeca/js-yaml/issues/600

**Comment by cristianvasquez** [comment]
Hi @dariuszkowalski-com , is fixed now in the new version
