### ISSUE TITLE
spaces after - 

### ISSUE THREAD

**Issue by dariuszkowalski-com** [cristianvasquez/obsidian-prettify#24]
I see that after format a list 
```
- A
- B
- C
```
after a `-` char there are added `3 spaces`.
As I understand Obsidian in normal mode add one space between char `-` and` [ ]` or `[x]`

the result file is incompatibile with very Toggle Checklist status 

and form me  it  makes a search expresion expensive for example for a todo items. 

`/- \[ \] \#TAG/`

**Comment by cristianvasquez** [comment]
Hi @dariuszkowalski-com, I updated the plugin to add the option of having 1 space.

**Comment by dariuszkowalski-com** [comment]
It doesn't work As espected:
 (Obsidian 0.10.2)  plugin 0.0.6
 
 1. one space:
 
![image](https://user-images.githubusercontent.com/37656900/102979356-3ff3e180-4506-11eb-9093-dd034e21024c.png)

  afer `-` one space -> ok, but intend has two spaces (two dots)
  
  Expected results:
  - [space] TEXT
  [space] -  [space] TEXT
  [space][space] -  [space] TEXT


2.  mixed
![image](https://user-images.githubusercontent.com/37656900/102979491-6ca7f900-4506-11eb-9a4a-c93db5f21413.png)

  - first inted has 3- space after a `-` char , secound  has 4 spaces which make an intend and 1 space after a  `-` 

Expected results:
- I do not know... mayby like a tab right now?
  
3. tab
![image](https://user-images.githubusercontent.com/37656900/102979689-b55fb200-4506-11eb-8205-cef13e2a8dcd.png)

  - first inted has 3- space after a `-` char , secound  has 4 spaces which make an intend and 3 spaces after a  `-` . there is no a TAB char at all
  
Expected results:
  - [1 space] TEXT
  [tab] -  [ 1space] TEXT
  [tab][tab] -  [ 1space] TEXT
