### ISSUE TITLE
Frontmatter bug

### ISSUE THREAD

**Issue by NomarCub** [cristianvasquez/obsidian-prettify#26]
I have some notes with YAML frontmatter and some without, and I don't want a formatter to change that.
If I disable 'Add new headers', then notes with existing frontmatter get formatted wrong. They're formatted right if 'Add new headers' is on, but I don't want to add new headers.
![](https://user-images.githubusercontent.com/5298006/102930904-a4c72180-449d-11eb-983c-c33c0feff286.gif)

**Comment by cristianvasquez** [comment]
Hi!, can you please give me a note to reproduce the behavior?

**Comment by NomarCub** [comment]
this was enough to reproduce

```
---
property: 'string'
---

anything

```

and it turns into this with 'Add new headers' off

```
---

## property: 'string'

anything

```

**Comment by cristianvasquez** [comment]
I see, 
There is a new version with the fix. Update and restart Obsidian, should work.

Thanks for reporting!.
