### ISSUE TITLE
Auto add quotes to front-matter

### ISSUE THREAD

**Issue by benwalio** [cristianvasquez/obsidian-prettify#28]
Is there any way to keep the prettifier from messing with other fields? I have some other static header fields that I'd like to stay that way (uuid, created at), but I'd like the updated at to update when running the prettifier. Is there a way to make it so the prettifier doesn't mess with fields it doesn't have in the template? or, can I put them in the template but somehow signify that they're 'static' and shouldn't be updated?

Excuse the crap video - wanted to get you something useable w/o doxxing myself too bad.

https://user-images.githubusercontent.com/13092287/103041063-4fdde680-4543-11eb-8526-baa17a33cd7c.mov

**Comment by cristianvasquez** [comment]
Hello, 

Thanks for reporting this and for the super video :)

Usually, frontmatter should be a YAML, meaning that the things you describe need to have quotes.

If you write the tag without quotes

```markdown
---
tag: #daily
---
```

The applications don' recognize it. For example, in Obsidian, in You get this as search result:

![image](https://user-images.githubusercontent.com/361916/103079960-31283000-45d5-11eb-8cc2-174f38c27b35.png)

Wereas if you describe it with quotes:

```markdown
---
tag: '#daily'
---
```

The applications recognize it correctly.

![image](https://user-images.githubusercontent.com/361916/103080007-456c2d00-45d5-11eb-90e9-2f8c2f462388.png)
 
In the meantime you can use quotes for the things you add, for example: 

```markdown
---
tags: ['#tag1','#tag2']
---

or

---
tags:
  - '#daily'
  - '#journal entry'
---
```

Probably I'll add something that auto-adds quotes and do not write 'null'  next week

Cheers!

**Comment by benwalio** [comment]
ah yeah, that'd do it! appreciate the help here!

**Comment by cristianvasquez** [comment]
Hi @benwalio ! I implemented the quotes. 

I also added a new one that adds hashtags found in the text and adds it to the frontmatter.
