### ISSUE TITLE
Invalid Frontmatter when use TAB in list

### ISSUE THREAD

**Issue by dariuszkowalski-com** [cristianvasquez/obsidian-prettify#33]
When I use a TAB in list

![image](https://user-images.githubusercontent.com/37656900/103491830-1cdf0100-4e27-11eb-8fd8-37a4efec908b.png)

I have got an message:
![image](https://user-images.githubusercontent.com/37656900/103491842-38e2a280-4e27-11eb-8b90-c9ee8eb34a09.png)

Expected result:
replease TABS by spaces to make it correct

**Comment by cristianvasquez** [comment]
Thanks for the report!

Definitely open to a Pull Request since I'm not sure when I'd be able to get to this.

**Comment by cristianvasquez** [comment]
I looked into the spec of yaml, only spaces are used. 

> In YAML block styles, structure is determined by indentation. In general, indentation is defined as a zero or more space characters at the start of a line. To maintain portability, tab characters must not be used in indentation, since different systems treat tabs differently. Note that most modern editors may be configured so that pressing the tab key results in the insertion of an appropriate number of spaces.    The amount of indentation is a presentation detail and must not be used to convey content information.


https://yaml.org/spec/1.2/spec.html#id2777534

**Comment by dariuszkowalski-com** [comment]
If so, maybe your plugin can change tabs to spaces?
Now when I enter a TAB i have got mentioned error when using you plugin
