### ISSUE TITLE
Keyboard shortcut has stopped working

### ISSUE THREAD

**Issue by jjspace** [cristianvasquez/obsidian-prettify#34]
Triggering prettifier has stopped working from the keyboard shortcut. Running it from the command pallet (`Ctrl + P`) still works but the shortcut no longer does regardless what I have set it to within Obsidian

**Comment by cristianvasquez** [comment]
I cannot reproduce this,

**Comment by jjspace** [comment]
So testing this a bit more it does seem like the keyboard shortcut is working as long as the keys trigger it. I had tried to put it on `Alt+Shift+F` which Obsidian seems to be ignoring? I't probably an issue on their side but I wouldn't mind some more confirmation whether you are able to use a command with this shortcut. It seems other combinations of `Alt+Shift+*Letter*` work fine just `F` is messing it up. There's also a possibility another one of my plugins is messing it up but I doubt that. I'll try and find a way to report directly to the Obsidian team.
