### ISSUE TITLE
Error with multiline math block: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by psyguy** [cristianvasquez/obsidian-prettify#35]
Hi,

I have a file for which I cannot run the plugin, as it throws the error `Cannot read property 'length' of undefined`.

I had some speculation into it (making a new note, removing stuff, etc.) and the error seems to be caused by multiline math blocks. For instance, I have this block in my text, which causes the error:

```
$$\begin{aligned}
		& y_{it} = \mu_i + x_{it}
		\\
		& x_{it} = \phi_i x_{i,t-1} + e_{it}
\end{aligned}$$
```

Though, if I add line breaks after and before the opening and closing `$$` (make as follows), the problem vanishes:

```
$$
\begin{aligned}
		& y_{it} = \mu_i + x_{it}
		\\
		& x_{it} = \phi_i x_{i,t-1} + e_{it}
\end{aligned}
$$
```

I think it'd be good if the issue is fixed.

Cheers.

**Comment by cristianvasquez** [comment]
Hi! I updated the plugin, and tried 

```
$$\begin{aligned}
		& y_{it} = \mu_i + x_{it}
		\\
		& x_{it} = \phi_i x_{i,t-1} + e_{it}
\end{aligned}$$
```
and throws no error.
