### ISSUE TITLE
On update should deleted tags be removed from frontmatter?

### ISSUE THREAD

**Issue by filmgal** [cristianvasquez/obsidian-prettify#39]
I noticed that updating the note does not remove tags that are no longer in the note.
Is it a bug or a feature?

**Comment by cristianvasquez** [comment]
I prefer to leave the tags in the note, so nothing is broken accidentally :)

**Comment by filmgal** [comment]
Fair enough. It just means having to remove action-type tags like "todo" in two places rather than one. But yeah, I get wanting to preserve other types of tags.
