### ISSUE TITLE
Adding "date updated" outside YAML header

### ISSUE THREAD

**Issue by psyguy** [cristianvasquez/obsidian-prettify#40]
Hi there,

I really like how the plugin updates `last updated` in the header, though I would like to have the dates as links to my daily notes, which is not supported by YAML.

For instance, I used to add the following lines as "header" to my notes:

``` 
First version: **[[2020-11-30 (Mon)]] | 11:19**

Latest version: **[[2021-01-11 (Mon)]] | 17:41** 

tags: #simulation
```

This made links to respective daily notes and I could trace the backlinks to see the progress I have made on a certain day.

Could there be a fix for this?

Thanks in advance!

**Comment by cristianvasquez** [comment]
I don't know if this has something to do with this plugin, 

But if the links are not detected from the YAML, I would put the links outside, just after :)

**Comment by psyguy** [comment]
Sure, the link issue of YAML is beyond the plugin. I was hoping that the plugin allowed updating fields (?) beyond the YAML header.
