### ISSUE TITLE
"List indent: tab" is not using tabs

### ISSUE THREAD

**Issue by dvcrn** [cristianvasquez/obsidian-prettify#41]
Hi I think I found a bug for using tabs for list indents

Using tabs for indentation: 
<img width="778" alt="Screen Shot 2021-01-19 at 15 54 41" src="https://user-images.githubusercontent.com/688326/104998548-c3a1df00-5a6e-11eb-81e3-79f64c822523.png">

Created a simple test note with a tab-indented list items

<img width="205" alt="Screen Shot 2021-01-19 at 15 54 31" src="https://user-images.githubusercontent.com/688326/104998537-c0a6ee80-5a6e-11eb-99a4-b00c65bd3e1f.png">

After running prettify: (all tabs gone and replaced with spaces) 

<img width="166" alt="Screen Shot 2021-01-19 at 15 54 35" src="https://user-images.githubusercontent.com/688326/104998541-c1d81b80-5a6e-11eb-9a7c-fa25f0be8fe8.png">

**Comment by jjspace** [comment]
This is the same problem reported again in #57 and should likely get fixed alongside #31

**Comment by cristianvasquez** [comment]
I updated the plugin to accept one space or a tab :)
