### ISSUE TITLE
Cannot create property tag

### ISSUE THREAD

**Issue by kiowalara** [cristianvasquez/obsidian-prettify#43]
When I run it, it says:
"Cannot create property 'tags' on '2021-01-21--18:49:20"

**Comment by cristianvasquez** [comment]
Hi thanks for reporting, but what says that? and when?

**Comment by cristianvasquez** [comment]
How can I explain that I prefer messages that  take care of my limited time ? :D

**Comment by kiowalara** [comment]
Hey
when I run the Markdown Prettifier, that's a dialog that pops up in the top right corner

**Comment by kiowalara** [comment]
My header template is like this:

'{{date:YYYY-MMMM-DD--HH:mm:ss}}'

I assume that the problem is here, I just don't know where, because well, I don't know

**Comment by cristianvasquez** [comment]
Hi @kiowalara 

I was able to reproduce, It's a misleading error message. 
can you try adding 'update date or something like that?

```markdown
Last update: '{{date:YYYY-MM-DD--date:HH:mm:ss}}'
```

**Comment by kiowalara** [comment]
Thank you, that worked!

However, when I tried around a bit and for example removed the ' or the : (I don't remember which one, but both led to weird results) the plugin proceeded to remove everything or parts of what was written in my md-file which was quite a shock.
I could restore it, but still.
