### ISSUE TITLE
Newly created headers DOES NOT use custom template

### ISSUE THREAD

**Issue by KarelWintersky** [cristianvasquez/obsidian-prettify#54]
My template:
```
date updated: '{{date:YYYY-MM-DD HH:mm:ss}}'
tags:
  - tag
  - tag
```

After `Ctrl-Alt-L` pressed (`Ctrl-Alt-Д` not supported, due to cyrillic) my empty document become:
```
---
date updated: '2021-03-23 16:12:30'

---
```

Obsidian 0.11.5 / Windows7
Plugin version: 0.0.8

**Comment by cristianvasquez** [comment]
It generates only one tag variable. That's what I intended :/

```markdown
---
date updated: 2021-10-27 18:43
tags:
  - tag
---
```

**Comment by KarelWintersky** [comment]
It is a bad solution.

**Comment by cristianvasquez** [comment]
I don't get what you mean. Two tags that are the same are conflated into one.

**Comment by KarelWintersky** [comment]
Damn! 
My template is:
```
date updated: '{{date:YYYY-MM-DD HH:mm:ss}}'
tags:
  - daily
  - tasks
```
but result is:
```
---
date updated: '2021-03-23 16:12:30'

---
```

**Comment by KarelWintersky** [comment]
works correctly at current 0.1.1 version.
Was broken at 0.0.8
