### ISSUE TITLE
Prettifier: removed -1 lines

### ISSUE THREAD

**Issue by jjspace** [cristianvasquez/obsidian-prettify#71]
It seems the sign is not properly flipped in this message. Can be reproduced by adding an extra line at the end of a file and prettifying. 

![20210805_115901](https://user-images.githubusercontent.com/8007967/128382633-79b85a11-1fd1-4101-89d1-21002f2e6dfd.png)

**Comment by cristianvasquez** [comment]
Fixed in 0.0.9
