### ISSUE TITLE
Can the Meta header show the updated date in preview mode?

### ISSUE THREAD

**Issue by Fierce-Ninja** [cristianvasquez/obsidian-prettify#76]
Currently I can see the updated date and tags in Edit mode after I run the prettifier command. But as soon as I switch to preview mode, I can only see tags in the Meta section, not the updated date.  Is there any workaround or fix for this?  Or am I doing something wrong that is preventing me from seeing the date in preview mode?

**Comment by cristianvasquez** [comment]
Hi @Fierce-Ninja I think you have the 'show frontmatter' option deactivated in Obsidian.  You can activate in settings -> editor -> show frontmatter option
