### ISSUE TITLE
Request: a way to have dates that are only computed at creation

### ISSUE THREAD

**Issue by huyz** [cristianvasquez/obsidian-prettify#77]
For my header template, I'd like to have:
```
Updated: {{date:YYYY-MM-DD HH:mm:ssZ}}
Created: {{date:YYYY-MM-DD HH:mm:ssZ}}
```

I do want the `Updated` every time I save, but I obviously want to keep `Created` the same.  I don't think there's a way to do that, right now, right?

**Comment by cristianvasquez** [comment]
I added this functionality in the new version (0.0.9)
