### ISSUE TITLE
I can't seem to be able to create a header with multiple lines

### ISSUE THREAD

**Issue by huyz** [cristianvasquez/obsidian-prettify#78]
If I set a template to:
```
Updated: {{date:YYYY-MM-DD HH:mm:ssZ}}
Created: {{date:YYYY-MM-DD HH:mm:ssZ}}
```

At first, it says it's valid YAML, but then the plugin doesn't work and, after I close the Settings dialog and reopen it, I get the error message `Your current header is NOT valid YAML`.

**Comment by cristianvasquez** [comment]
I couldn't reproduce your error, but I updated the plugin and now there are two templates, one for creation and one for updates. 

cheers
