### ISSUE TITLE
Prettier

### ISSUE THREAD

**Issue by MarioRicalde** [cristianvasquez/obsidian-prettify#8]
@cristianvasquez do you have any plans on using something like https://prettier.io/ for formatting?

**Comment by cristianvasquez** [comment]
Hi @MarioRicalde, I was not aware of that one, perhaps it's a good idea.

**Comment by cristianvasquez** [comment]
@MarioRicalde I think is it's a good idea to use this, but how to include it? it's 18Mb 

Perhaps one could just call it. Do you use it?

**Comment by ivan-lednev** [comment]
There is an obsidian plugin that does exactly this: formats files using Prettier: https://github.com/hipstersmoothie/obsidian-plugin-prettier
