### ISSUE TITLE
Running prettify inserts backslashes into links with underscores

### ISSUE THREAD

**Issue by euphonics** [cristianvasquez/obsidian-prettify#80]
Great plug-in, have been using it for a long time. 

Ever since the recent update, whenever I run the `Markdown Prettierfier: Run` command, unwanted backslashes are inserted into my wikilinks. I can reproduce this in 2 different vaults on 2 different computers, both running Windows 10.

For example, if I have a note with the following link:

```
[[test_1]] 
```
...and then I ran the `Markdown Prettierfier: Run` command, I will be left with:

```
[[test\_1]]
```

If I run it again, then I will have:

```
[[test\\\_1]]
```

And so on. Now I don't want to run the command anymore because doing so means that I need to go and delete a bunch of backslashes later on.

Thanks

**Comment by Goetterwind** [comment]
This is pretty annoying in the current version, as it breaks all my links to any Bibtex-key I generate using the 'Citations' plugin in the 'prettified' file.

I am running Windows (10 and 11). I will try it on my Linux-distro, to see if this problem persists there as well.

edit: on Linux the same issue

**Comment by Goetterwind** [comment]
It only seems to appear, if after the underscore there is a number: It will generate 
`xxx_123` to `xxx\_123`, but will leave `xxx_yyy` alone...

edit: It seems that 0.0.8 is working properly, so until this is fixed, I will stick with the older version...

**Comment by cristianvasquez** [comment]
@euphonics @Goetterwind, thanks for reporting this. I've updated a new version

Cheers!
