### ISSUE TITLE
Error being reported -  Cannot handle unknown node `blockquote`

### ISSUE THREAD

**Issue by ms3056** [cristianvasquez/obsidian-prettify#85]
I have a blockquote at the end of my note and for some reason suddenly it is tripping an error. The issue is with this at the end of the note - if I remove the blockquote the error goes away:

```
> What is the one sentence summary of how you
change the world? Always work hard on something
uncomfortably exciting!
— <cite>Larry Page</cite>
```

![image](https://user-images.githubusercontent.com/23712700/142381495-f8b13479-1838-4894-bc10-7fbbf120c00f.png)

**Comment by rodrigo-rufino** [comment]
Same here!

**Comment by cristianvasquez** [comment]
I introduced this error in the last version, I hope to fix it tomorrow or something like that.

https://github.com/cristianvasquez/obsidian-prettify/issues/84

**Comment by cristianvasquez** [comment]
Thanks for the report, it's fixed now.
