### ISSUE TITLE
Prettifier not compatible with the new editor of Obsidian v0.13.14

### ISSUE THREAD

**Issue by shiw13** [cristianvasquez/obsidian-prettify#89]
Hi:

After Obsidian updated to v0.13.14, Prettifier is not working.  
Enable legacy editor and the plugin can work normally. Can you fix this? thanks.

![image](https://user-images.githubusercontent.com/18344826/147195141-83308332-2f2d-4fa7-811e-eb46562e2adc.png)

**Comment by OxSon** [comment]
Seems to work for me on v0.13.19

**Comment by shiw13** [comment]
After I reinstall Prettifier, it can work now.
